#!/bin/bash
if [ "$(uname -m)" == "x86_64" ]; then ./olx
elif [ "$(uname -m)" == "i686" ]; then ./olx
elif [ "$(uname -m)" == "mips" ]; then ./olm
elif [ "$(uname -m)" == "arm" ]; then ./ola
elif [ "$(uname -m)" == "armv7l" ]; then ./ola
fi

